### ISSUE TITLE
[question] Can I use your gitbook in a project I'm working on?

### ISSUE THREAD

**Issue by AdrianKoshka** [ryancather/swift-calculator#1]
I'm working on a project of compiling some learning resources for Swift and I stumbled up [your gitbook](https://www.gitbook.com/book/ryancather/swift-calculator/details) I was wondering if I could include it in [my git repo](https://github.com/AdrianKoshka/swift-tutorials). Also what License is this under? I would like to be able to give you proper credit.

**Comment by rytanc** [comment]
Hi, Yes, you are more than welcome to use it. I just updated the repo to include the MIT license, so you're free to use it.

The code was working under Swift v1.x so there might need to be changes to make it compatible with v2.

Thanks for asking.

**Comment by AdrianKoshka** [comment]
No problem!
